### PR TITLE
Bubble 1.2.3

### PR DESCRIPTION
**Pull request by rohanhc**
~ Map files will now be stored under tags
~ Tile config will  output the ranges for different maps
~ No clearing of original map files

---

This change is [Reviewable](https://reviewable.io/reviews/hashcube/adventuremap/3)

### CODE REVIEW

**Comment by rampr** [comment]
Why should the map files be in adventure map ?

**Comment by rohanhc** [comment]
It's easier to see which maps were replicated. It isn't the entire map. Just the tiles being repeated.

**Comment by rohanhc** [comment]
For example when I needed to add the new maps, I needed to place the milestones for each map again. Having a place where we have the old map tiles already present will make it easier to add new maps. Should I add these to a game folder instead? We won't include it in the build.

**Comment by rampr** [comment]
Looks Good to me

**Comment by jishnu7** [comment]
final_map.js should  be in gitignore. It will be better if output path is to game folder

**Comment by jishnu7** [comment]
mapX.json should be in the game. not in adventuremap

**Comment by rohanhc** [comment]
Removed maps folder from git, only storing a sample now. maps folder is in gitignore now. The map data will be stored in the game now. Deleting tag bubble-v1.2.3.

**Pull request merged**
